import setuptools


with open("README.md") as fp:
    long_description = fp.read()


setuptools.setup(
    name="service_catalog",
    version="0.2",
    description="CICD Pipeline for testing and deploying Service Catalog products for MDP, MAP and MEP users",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Malte Walkowiak",
    package_dir={"": "service_catalog"},
    packages=setuptools.find_packages(where="service_catalog"),
    install_requires=[
        "aws-cdk.core==1.51.0",
        "aws-cdk.aws-lambda==1.51.0",
        "aws-cdk.aws-codepipeline==1.51.0",
        "aws-cdk.aws-codepipeline-actions==1.51.0",
        "aws-cdk.aws-codebuild==1.51.0",
        "aws-cdk.aws-servicecatalog==1.51.0",
        "aws-cdk.aws-iam==1.51.0",
        "aws-cdk.aws-s3==1.51.0",
        "aws_cdk.aws_cloudwatch==1.51.0",
        "aws_cdk.aws_cloudwatch_actions==1.51.0",
        "aws_cdk.aws_lambda_event_sources==1.51.0",
        "aws_cdk.aws_sns==1.51.0",
        "aws_cdk.aws_events_targets==1.51.0",
        "aws_cdk.aws_cloudformation==1.51.0",
        "aws_cdk.aws_events==1.51.0",
        "aws_cdk.aws_logs==1.51.0",
        "aws_cdk.aws_servicecatalog==1.51.0",
        "aws_cdk.aws_sagemaker==1.51.0",
        "aws_cdk.aws_glue==1.51.0",
        "aws_cdk.aws_budgets==1.51.0",
        "aws_cdk.aws_cloudwatch==1.51.0",
        "aws_cdk.aws_codecommit==1.51.0",
        "aws_cdk.aws_rds==1.51.0",
        "aws_cdk.aws_ec2==1.51.0",
        "aws_cdk.aws_dynamodb==1.51.0",
        "aws_cdk.aws_kms==1.51.0",
        "aws_cdk.aws_autoscaling==1.51.0",
        "aws_cdk.aws_cloudformation==1.51.0",
        "cfn-lint",
        "git-remote-codecommit",
        "configparser",
        "boto3",
        "cfnresponse",
        "botocore",
        "python-dateutil",
        "PyYAML",
        "setuptools",
        "pydocstyle",
        "pre-commit",
        "flake8",
    ],
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: JavaScript",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Topic :: Software Development :: Code Generators",
        "Topic :: Utilities",
        "Typing :: Typed",
    ],
)
